version: "3.9"

services:
  app:
    build: .
    image: cliente-api
    container_name: cliente-api
    environment:
      MONGO_DB_HOST: "${MONGO_DB_HOST}"
      MONGO_DB_PORT: "${MONGO_DB_PORT}"
      MONGO_DB_NAME: "${MONGO_DB_NAME}"
    ports:
      - "8080:8080"
    depends_on:
      mongo-db:
        condition: service_healthy
    restart: always
    networks:
      - client-api-network

  mongo-db:
    image: mongo
    restart: always
    container_name: cliente-api-mongo
    environment:
      MONGO_DB_PORT: "${MONGO_DB_PORT}"
      MONGO_DB_NAME: "${MONGO_DB_NAME}"
    ports:
      - "27017:27017"
    networks:
      - client-api-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:27017" ]

networks:
  cliente-network:
    driver: bridge
