apiVersion: v1
kind: Pod
metadata:
  name: cliente-api-mongo
  labels:
    app: cliente-api-mongo
spec:
  containers:
    - name: cliente-api-mongo
      image: mongo:6.0.13
      ports:
        - containerPort: 27017
      env:
            - name: MONGO_DB_USERNAME
              value: "root"
            - name: MONGO_DB_ROOT_PASSWORD
              value: "123"
            - name: MONGO_DB_PORT
              value: "27017"
            - name: MONGO_DB_NAME
              value: "clientedb"