apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-api-deployment
  labels:
    app: cliente-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cliente-api
  template:
    metadata:
      labels:
        app: cliente-api
    spec:
      containers:
        - name: cliente-api
          image: melissa2019/api-0.0.1-snapshot:latest
          ports:
            - containerPort: 80
          env:
            - name: MONGO_DB_HOST
              value: mysql.host
            - name: MONGO_DB_NAME
              value: "clientes"
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 2
