apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-api-deployment
  labels:
    app: cliente-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cliente-api
  template:
    metadata:
      labels:
        app: cliente-api
    spec:
      containers:
        - name: cliente-api
          image: icarojurado/api-0.0.1-snapshot:latest
          ports:
            - containerPort: 80
          env:
            - name: MONGO_DB_HOST
              value: "cliente-api-mongo-service"
            - name: MONGO_DB_PORT
              value: "27017"
            - name: MONGO_DB_NAME
              value: "clientedb"
            - name: DATABASE_MONGO_USERNAME
              value: "root"
            - name: DATABASE_MONGO_PASSWORD
              value: "123"
            - name: RABBITMQ_HOST
              value: "production-rabbitmq-service"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: production-rabbitmq
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: production-rabbitmq
                  key: password
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 2
