apiVersion: v1
kind: Service
metadata:
  name: cliente-api-lb
  labels:
    app: cliente-api-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: cliente-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080